[package]
name = "iml-manager-client"
version = "0.2.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
iml-manager-env = { path = "../iml-manager-env", version = "0.2.0" }
iml-request-retry = { path = "../iml-request-retry", version = "0.2" }
reqwest = { version = "0.10", features = ["default-tls", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
url = "2.1"