[package]
name = "iml-devices"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
tokio = { version = "0.2", features = ["macros"] }
tokio-util = { version = "0.2", features = ["codec"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
iml-wire-types = { path = "../../iml-wire-types", version = "0.2", features = ["postgres-interop"] }
iml-postgres = { path = "../../iml-postgres", version = "0.1"}
iml-rabbit = { path = "../../iml-rabbit", version = "0.1.0" }
iml-service-queue = { path = "../iml-service-queue", version = "0.1.0" }
tracing = "0.1"
tracing-subscriber = "0.1"
test-case = "1.0.0"

[dev-dependencies]
insta = "0.12"
