[package]
name = "iml-mailbox"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
futures = "0.3"
iml-manager-env = { path = "../iml-manager-env", version = "0.1.0" }
iml-fs = { path = "../iml-fs", version = "0.1" }
tokio = "0.2"
warp = "0.2"
tracing = "0.1"
tracing-subscriber = "0.1"

[dev-dependencies]
pretty_assertions = "0.6.1"
tempdir = "0.3"