[package]
version = "0.1.0"
name = "iml-gui"
repository = "https://github.com/whamcloud/integrated-manager-for-lustre"
authors = ["IML Team <iml@whamcloud.com>"]
description = "The IML GUI"
categories = ["wasm", "rust", "tailwindcss", "seed"]
license = "MIT"
readme = "./README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "0.3"

[dependencies]
chrono = { version = "0.4", features = ["wasmbind"] }
im = { version = "14.1", features = ["serde"] }
iml-wire-types = { path = "../../iml-wire-types", version = "0.2" }
js-sys = "0.3"
natord = "1.0"
number-formatter = { path = "../../number-formatter", version = "0.1" }
seed = "0.5.1"
serde = { version = "1", features = ['derive'] }
serde_json = "1.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[dependencies.web-sys]
version = "^0.3"
features = [
  "DomRect",
  "Element",
  "EventSource",
  "MessageEvent",
  "Navigator",
  "Notification",
  "NotificationOptions",
  "NotificationPermission",
  "ServiceWorkerContainer",
  "ServiceWorkerRegistration",
  "Window",
]

[profile.release]
lto = true
opt-level = 's'
