[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-ostpool"
version = "0.5.0"

[dependencies]
futures = "0.3"
iml-postgres = {path = "../../iml-postgres", version = "0.5"}
iml-rabbit = {path = "../../iml-rabbit", version = "0.5"}
iml-service-queue = {path = "../iml-service-queue", version = "0.5"}
iml-tracing = {version = "0.5", path = "../../iml-tracing"}
iml-wire-types = {path = "../../iml-wire-types", version = "0.5"}
tokio = {version = "0.2", features = ["rt-threaded", "macros"]}
tracing = "0.1"
