[package]
name = "iml-ostpool"
version = "0.3.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
futures-util = "0.3"
iml-postgres = { path = "../../iml-postgres", version = "0.3" }
iml-service-queue = { path = "../iml-service-queue", version = "0.3" }
iml-tracing = { version = "0.2", path="../../iml-tracing"}
iml-wire-types = { path = "../../iml-wire-types", version = "0.3" }
tokio = "0.2"
tracing = "0.1"
