[package]
name = "iml-warp-drive"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.19"
tracing = "0.1"
tracing-subscriber = "0.1"
tokio = "0.2.0-alpha.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.7", features = ["v4"] }
warp = { git = "https://github.com/seanmonstar/warp.git" }
iml-manager-env = { path = "../iml-manager-env", version = "0.1.0" }
iml-rabbit = { path = "../iml-rabbit", version = "0.1.0" }
iml-postgres = { path = "../iml-postgres", version = "0.1.0" }
iml-wire-types = { path = "../iml-wire-types", version = "0.2", features = ["postgres-interop"] }
iml-manager-client = { path = "../iml-manager-client", version = "0.1" }
tokio-runtime-shutdown = { path = "../tokio-runtime-shutdown", version = "0.1" }