[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-warp-drive"
version = "0.5.0"

[dependencies]
futures = "0.3"
im = {version = "15.0", features = ["serde"]}
iml-manager-client = {path = "../iml-manager-client", version = "0.5"}
iml-manager-env = {path = "../iml-manager-env", version = "0.5"}
iml-postgres = {path = "../iml-postgres", version = "0.5"}
iml-rabbit = {path = "../iml-rabbit", version = "0.5"}
iml-tracing = {version = "0.5", path = "../iml-tracing"}
iml-wire-types = {path = "../iml-wire-types", version = "0.5", features = ["postgres-interop"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
tokio = {version = "0.2", features = ["macros", "rt-threaded"]}
tokio-runtime-shutdown = {path = "../tokio-runtime-shutdown", version = "0.5"}
tracing = "0.1"
uuid = {version = "0.8", features = ["v4"]}
warp = "0.2"
