[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-stats"
version = "0.5.0"

[dependencies]
futures = "0.3"
iml-influx = {path = "../../iml-influx", version = "0.5", features = ["with-db-client"]}
iml-manager-env = {path = "../../iml-manager-env", version = "0.5"}
iml-rabbit = {path = "../../iml-rabbit", version = "0.5"}
iml-service-queue = {path = "../iml-service-queue", version = "0.5"}
iml-tracing = {version = "0.5", path = "../../iml-tracing"}
iml-wire-types = {path = "../../iml-wire-types", version = "0.5"}
lustre_collector = "0.2.16"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"
tokio = {version = "0.2", features = ["macros", "rt-threaded"]}
tracing = "0.1"
url = "2.1.1"
