[package]
name = "iml-environment"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
seed = "=0.4.0"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"]}
web-sys = { version = "0.3", features = ["HtmlDocument"] }
regex = "1"

[dev-dependencies]
wasm-bindgen-test = "0.2"
insta = "0.11"
