language: python
python: "2.7"
sudo: required
services:
  - docker
  - postgresql
addons:
  postgresql: "9.2"
  apt:
    update: true
    packages:
      - postgresql-server-dev-9.2
jobs:
  include:
    - stage: test
      name: "Docker build Test"
      script:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-x86_64 > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
        - cd docker
        - docker build --rm -t imlteam/manager-service-base -f base.dockerfile ../
        - docker build --rm -t imlteam/manager-nginx -f nginx.dockerfile ../
        - docker-compose build
    - stage: test
      name: "Unit Tests"
      install:
        - pip install -r requirements.txt
        - pip install -r requirements.test
      before_script:
        - psql -c "CREATE USER chroma;" -U postgres
        - psql -c "ALTER USER chroma CREATEDB;" -U postgres
        - psql -c "CREATE DATABASE chroma OWNER chroma;" -U postgres
      script:
        - export IML_DISABLE_THREADS=1
        - echo "CRYPTO_FOLDER='./'" > local_settings.py
        - echo -e "/^DEBUG =/s/= .*$/= True/\nwq" | ed settings.py 2>/dev/null
        - python -W always manage.py test tests/unit/
    - stage: test
      name: "Behave tests"
      install:
        - pip install -r requirements.txt
        - pip install -r requirements.test
      before_script:
        - psql -c "CREATE USER chroma;" -U postgres
        - psql -c "ALTER USER chroma CREATEDB;" -U postgres
        - psql -c "CREATE DATABASE chroma OWNER chroma;" -U postgres
      script:
        - export IML_DISABLE_THREADS=1
        - behave --format plain tests/feature/cli/features
    - stage: test
      name: "Service tests"
      script:
        - docker run -dit --privileged --name systemd --mount type=bind,source="$(pwd)",target=/integrated-manager-for-lustre  -v /sys/fs/cgroup:/sys/fs/cgroup:ro centos/systemd
        - docker exec -i systemd bash -c "./integrated-manager-for-lustre/tests/framework/services/runner.sh"
    - stage: test
      name: "Format Check"
      python: "3.6"
      install:
        - pip install black
      script:
        - black --check ./
    - stage: test
      name: "iml-warp-drive Build Check"
      language: rust
      rust: 1.33.0
      cache: cargo
      script:
        - docker run -dit --cap-add=SYS_ADMIN --privileged --name mock imlteam/mock /usr/sbin/init
        - docker cp -a ./ mock:/builddir
        - docker exec -it mock bash -xec 'chown -R root:root /builddir'
        - docker exec -it mock bash -xec 'yum install -y dnf dnf-plugins-core'
        - docker exec -it mock bash -xec 'dnf copr enable -y managerforlustre/buildtools'
        - docker exec -it mock bash -xec 'cd /builddir/iml-warp-drive && make -f .copr/Makefile srpm outdir=/tmp/'
    - stage: test
      name: "Rust Tests"
      language: rust
      rust: 1.33.0
      cache: cargo
      services: rabbitmq
      script:
        - cargo build --verbose
        - cargo test --verbose
    - stage: test
      name: "Rust Linting Check"
      language: rust
      rust: 1.33.0
      before_script:
        - rustup component add clippy
      script:
        - cargo clippy
    - stage: test
      name: "Rust Format Check"
      language: rust
      rust: 1.33.0
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
    - stage: cd
      git:
        depth: 999999
      name: "Continuous Deployment (Copr)"
      script:
        - include/travis/copr-deploy.sh prepare
        - ./travis_wait "./include/travis/run_in_centos7_docker.sh include/travis/copr-deploy.sh build_srpm"
    - stage: cd
      git:
        depth: 999999
      name: "Continuous Deployment (Docker)"
      script:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-x86_64 > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - cd docker
        - docker build --rm -t imlteam/manager-service-base -f base.dockerfile ../
        - docker push imlteam/manager-service-base
        - docker build --rm -t imlteam/manager-nginx -f nginx.dockerfile ../
        - docker push imlteam/manager-nginx
        - docker-compose build
        - docker-compose push
    - stage: cd
      name: "iml-warp-drive Continuous Deployment (Copr)"
      script:
        - export OWNER=managerforlustre
        - export PROJECT=manager-for-lustre-devel
        - export SRPM_PATH='/tmp/*.src.rpm'
        - docker run -dit --entrypoint "/bin/bash" --name "copr" -e OWNER="$OWNER" -e PROJECT="$PROJECT" -e SRPM_PATH="$SRPM_PATH" -e KEY="$encrypted_253525cedcf6_key" -e IV="$encrypted_253525cedcf6_iv" -v $(pwd):/build:rw imlteam/copr
        - docker exec -it copr bash -xec 'yum copr enable -y managerforlustre/buildtools'
        - docker exec -it copr bash -xec 'cd /build/iml-warp-drive && make -f .copr/Makefile srpm outdir=/tmp/'
        - docker exec -it copr bash -xec 'create_build'
stages:
  - test
  - name: cd
    if: branch = master AND type = push AND fork = false
