[workspace]
members = [
    'iml-agent-comms',
    'iml-agent',
    'iml-cmd',
    'iml-fs',
    'iml-mailbox',
    'iml-manager-cli',
    'iml-manager-client',
    'iml-manager-env',
    'iml-orm',
    'iml-postgres',
    'iml-rabbit',
    'iml-request-retry',
    'iml-services/iml-action-runner',
    'iml-services/iml-devices',
    'iml-services/iml-ostpool',
    'iml-services/iml-postoffice',
    'iml-services/iml-service-queue',
    'iml-services/iml-stratagem',
    'iml-util',
    'iml-warp-drive',
    'iml-wire-types',
    'liblustreapi-types',
    'liblustreapi',
    'number-formatter',
    'tokio-runtime-shutdown',
    'version-utils',
]

exclude = [
    'iml-gui/crate'
]
