[workspace]
members = [
    'iml-wire-types',
    'iml-agent-comms',
    'iml-rabbit',
    'iml-manager-env',
    'iml-agent',
    'iml-services',
    'liblustreapi-types',
    'liblustreapi',
    'tokio-runtime-shutdown',
    'iml-warp-drive',
    'iml-mailbox',
    'iml-manager-cli',
    'iml-manager-client',
    'iml-fs',
    'iml-util',
    'iml-postgres'
]
