[workspace]
members = [
    'iml-action-client',
    'iml-agent-comms',
    'iml-agent',
    'iml-api-utils',
    'iml-api',
    'iml-cmd',
    'iml-fs',
    'iml-influx',
    'iml-job-scheduler-rpc',
    'iml-mailbox',
    'iml-manager-cli',
    'iml-manager-client',
    'iml-manager-env',
    'iml-orm',
    'iml-postgres',
    'iml-rabbit',
    'iml-request-retry',
    'iml-services/iml-action-runner',
    'iml-services/iml-device',
    'iml-services/iml-ntp',
    'iml-services/iml-ostpool',
    'iml-services/iml-ntp',
    'iml-services/iml-postoffice',
    'iml-services/iml-service-queue',
    'iml-services/iml-stats',
    'iml-sfa',
    'iml-system-test-utils',
    'iml-task-runner',
    'iml-timer',
    'iml-systemd',
    'iml-timer',
    'iml-tracing',
    'iml-util',
    'iml-warp-drive',
    'iml-wire-types',
    'liblustreapi-types',
    'liblustreapi',
    'number-formatter',
    'tokio-runtime-shutdown',
    'version-utils',
    'wbem-client'
]

exclude = [
    'iml-gui/crate',
    'iml-system-rpm-tests',
    'iml-system-docker-tests',
]
