[package]
name = "iml-rabbit"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
lapin-futures = "0.18.0"
tokio = "0.1"
failure = "0.1.5"
futures = "0.1"
log = "0.4"
iml-wire-types = { path = "../iml-wire-types", version = "0.2" }
iml-manager-env = { path = "../iml-manager-env", version = "0.1.0" }