[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-rabbit"
version = "0.3.0"

[dependencies]
deadpool-lapin = {git = "https://github.com/whamcloud/deadpool", branch = "rustls", default-features = false, features = ["rustls"]}
futures = "0.3"
iml-manager-env = {path = "../iml-manager-env", version = "0.3"}
iml-wire-types = {path = "../iml-wire-types", version = "0.3"}
lapin = {path = "/home/mkpankov/work/lapin", version = "1.2", default-features = false, features = ["rustls"]}
serde_json = "1"
thiserror = "1.0"
tokio-amqp = {path = "/home/mkpankov/work/lapin/tokio", version = "0.1"}
tracing = "0.1"
warp = {version = "0.2", optional = true}

[dev-dependencies]
tokio = {version = "0.2", features = ["macros", "rt-threaded"]}
warp = "0.2"

[features]
warp-filters = ["warp"]
