[package]
name = "iml-agent"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
description = "Core library for Integrated Manager for Lustre Agent"
license = "MIT"
repository = "https://github.com/whamcloud/integrated-manager-for-lustre/tree/master/iml-agent"

[dependencies]
byte-unit = "=2.1"
bytes = "0.5"
chrono = "0.4"
device-types = "0.1.3"
console = "0.9"
dns-lookup = "1"
dotenv = "0.15"
elementtree = "0.5"
exitcode = "1.1"
futures = "0.3"
futures-util = "0.3.1"
http = "0.2"
iml-cmd = { path = "../iml-cmd", version = "0.1.0" }
iml-fs = { path = "../iml-fs", version = "0.1.0" }
iml-util = { path = "../iml-util", version = "0.1.0" }
iml-wire-types = { path = "../iml-wire-types", version = "0.2" }
inotify = "0.8"
lazy_static = "1.4.0"
libc = "0.2"
liblustreapi = { path = "../liblustreapi", version = "0.1" }
native-tls = "0.2"
parking_lot = "0.9"
prettytable-rs = "0.8"
reqwest = { version = "0.10", features = ["default-tls", "native-tls", "json", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
spinners = "1.2"
stream-cancel = "0.5"
strfmt = "0.1.6"
structopt = "0.2"
tokio = { version = "0.2", features = ["fs", "process", "macros", "net"] }
tokio-util = { version = "0.2", features = ["codec"] }
tracing = "0.1"
tracing-subscriber = "0.1"
url = "2.1"
uuid = { version = "0.7", features = ["v4"] }
v_hist = "0.1.2"
version-utils = { path = "../version-utils", version = "0.1.0" }

[dependencies.regex]
version = "1.3"
default-features = false
features = ["std"]

[dev-dependencies]
mockito = "0.22.0"
pretty_assertions = "0.6.1"
insta = "0.12"
tempfile = "3.1.0"

[[bin]]
name = "iml-agent-daemon"
path = "src/main.rs"

[[bin]]
name = "iml-agent"
path = "src/cli.rs"
