[package]
name = "iml-agent"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
description = "Core library for Integrated Manager for Lustre Agent"
license = "MIT"
repository = "https://github.com/whamcloud/integrated-manager-for-lustre/tree/master/iml-agent"

[dependencies]
bytes = "0.4"
byte-unit = "=2.1"
chrono = "0.4"
dns-lookup = "1"
elementtree = "0.5"
env_logger = "0.7"
exitcode = "1.1"
futures = "0.1.29"
lazy_static = "1.3.0"
termion = "1"
spinners = "1.0.0"
libc = "0.2"
log = "0.4"
prettytable-rs = "0.8"
reqwest = { version = "0.9", features = ["rustls-tls"] }
hyper = "0.12"
http = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
structopt = "0.2.18"
tokio = "0.1"
tokio-timer = "0.2"
tokio-process = "0.2"
tokio-threadpool = "0.1"
tokio-tls = "0.2"
tracing = "0.1"
tracing-futures = "0.0.1-alpha.1"
tracing-fmt = "0.0.1-alpha.3"
native-tls = "0.2"
url = "1.7"
v_hist = "0.1.1"
uuid = { version = "0.7", features = ["v4"] }
parking_lot = "0.9"
iml-wire-types = { path = "../iml-wire-types", version = "0.2" }
liblustreapi = { path = "../liblustreapi", version = "0.1" }
iml-fs = { path = "../iml-fs", version = "0.1.0" }

[dev-dependencies]
mockito = "0.20.0"
pretty_assertions = "0.6.1"

[[bin]]
name = "iml-agent-daemon"
path = "src/main.rs"

[[bin]]
name = "iml-agent"
path = "src/cli.rs"
