[package]
name = "iml-agent"
version = "0.1.0-alpha.1"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
description = "Core library for Integrated Manager for Lustre Agent"
license = "MIT"
repository = "https://github.com/whamcloud/integrated-manager-for-lustre/tree/master/iml-agent"

[dependencies]
chrono = "0.4"
csv = "1"
dns-lookup = "1"
env_logger = "0.6.1"
exitcode = "1.1"
futures = "0.1.27"
lazy_static = "1.3.0"
termion = "1"
spinners = "1.0.0"
libc = "0.2.55"
log = "0.4.6"
prettytable-rs = "0.8"
reqwest = { version = "0.9", features = ["default-tls", "tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
structopt = "0.2.15"
tempfile = "3.0.8"
tokio = "0.1.20"
tokio-timer = "0.2.11"
tokio-process = "0.2.3"
tokio-threadpool = "0.1.14"
url = "1.7.2"
v_hist = "0.1.1"
uuid = { version = "0.7", features = ["v4"] }
parking_lot = "0.8"
iml-wire-types = { path = "../iml-wire-types", version = "0.1.0" }
liblustreapi = { path = "../liblustreapi", version = "0.1" }
stream-lines = { git = "https://github.com/softprops/stream-lines" }

[dev-dependencies]
mockito = "0.17.1"
pretty_assertions = "0.6.1"
tempdir = "0.3"

[[bin]]
name = "iml-agent-daemon"
path = "src/main.rs"

[[bin]]
name = "iml-agent"
path = "src/cli.rs"
