[package]
name = "iml-wire-types"
description = "Shared types for the IML project"
license = "MIT"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.39"