[package]
name = "iml-util"
description = "IML Util Library"
license = "MIT"
version = "0.2.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
iml-wire-types = { path = "../iml-wire-types", version = "0.2" }
serde = { version = "1", features = ['derive'] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["net", "stream"] }
tracing = "0.1"

[lib]
path = "util.rs"
