[package]
authors = ["IML Team <iml@whamcloud.com>"]
description = "IML Util Library"
edition = "2018"
license = "MIT"
name = "iml-util"
version = "0.5.0"

[dependencies]
futures = "0.3"
iml-wire-types = {path = "../iml-wire-types", version = "0.5"}
serde = {version = "1", features = ['derive']}
serde_json = "1.0"
tokio = {version = "0.2", features = ["net", "stream"]}
tracing = "0.1"

[lib]
path = "util.rs"
