[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-graphql-queries"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1"
