[package]
name = "iml-stratagem"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
seed = "=0.3.7"
serde = { version = "1", features = ['derive'] }
serde_json = "1.0"
iml-wire-types = "0.1"
iml-grafana-chart = { path = "../iml-grafana-chart", version = "0.1" }
bootstrap-components = { path = "../bootstrap-components", version = "0.1" }
iml-sleep = { path = "../iml-sleep", version = "0.1" }
wasm-bindgen = "0.2.48"
log = "0.4"
futures = "0.1"

[dev-dependencies]
wasm-bindgen-test = "0.2"

[dev-dependencies.web-sys]
version = "0.3.25"
features = [
  "Response"
]