[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-system-test-utils"
version = "0.5.0"

[dependencies]
async-trait = "0.1"
futures = "0.3"
iml-cmd = {version = "0.5", path = "../iml-cmd"}
iml-fs = {version = "0.5", path = "../iml-fs"}
iml-graphql-queries = {version = "0.5", path = "../iml-graphql-queries"}
iml-wire-types = {version = "0.5", path = "../iml-wire-types"}
petgraph = "0.5"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
thiserror = "1.0"
tokio = {version = "0.2", features = ["process", "macros", "fs", "time"]}
tracing = "0.1"

[dev-dependencies]
insta = "0.16.1"
