[package]
name = "iml-system-test-utils"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
iml-cmd = { version = "0.2.0", path = "../iml-cmd" }
iml-systemd = { version = "0.1.0", path = "../iml-systemd" }
iml-wire-types = { version = "0.2.0", path = "../iml-wire-types" }
tokio = {version="0.2", features=["process", "macros", "fs"]}
