version: "3.7"
services:
  postgres:
    restart: on-failure
  influxdb:
    restart: on-failure
  grafana:
    restart: on-failure
  rabbit:
    restart: on-failure
  nginx:
    restart: on-failure
  device:
    restart: on-failure
  ntp:
    restart: on-failure
  corosync:
    restart: on-failure
  gunicorn:
    restart: on-failure
  http-agent:
    restart: on-failure
  iml-agent-comms:
    restart: on-failure
  job-scheduler:
    restart: on-failure
  plugin-runner:
    restart: on-failure
  journal:
    restart: on-failure
  iml-ostpool:
    restart: on-failure
  iml-stats:
    restart: on-failure
  iml-warp-drive:
    restart: on-failure
  setup:
    restart: on-failure
  iml-action-runner:
    restart: on-failure
  iml-api:
    restart: on-failure
  iml-postoffice:
    restart: on-failure
secrets:
  iml_pw:
    file: /tmp/iml_pw
