[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-manager-cli"
version = "0.3.0"

[dependencies]
combine = "=4.1.0"
console = "0.11"
dialoguer = "0.6"
dotenv = "0.15"
futures = "0.3"
hostlist-parser = "0.1.3"
iml-api-utils = {path = "../iml-api-utils", version = "0.3"}
iml-influx = {path = "../iml-influx", version = "0.1"}
iml-manager-client = {path = "../iml-manager-client", version = "0.3"}
iml-postgres = {path = "../iml-postgres", version = "0.3"}
iml-tracing = {version = "0.2", path = "../iml-tracing"}
iml-wire-types = {path = "../iml-wire-types", version = "0.3", features = ["cli"]}
indicatif = "0.14"
lazy_static = "1.4"
number-formatter = {path = "../number-formatter", version = "0.1"}
prettytable-rs = "0.8"
reqwest = {version = "0.10", default-features = false, features = ["rustls-tls", "json"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_yaml = "0.8"
spinners = "1.2.0"
structopt = "0.3"
thiserror = "1.0"
tokio = {version = "0.2", features = ["macros", "io-std", "io-util", "fs", "rt-threaded"]}
tracing = "0.1"

[dependencies.regex]
default-features = false
features = ["std"]
version = "1.3"

[dev-dependencies]
insta = "0.16"

[[bin]]
name = "iml"
path = "src/main.rs"

[[bin]]
name = "iml-config"
path = "src/config-main.rs"
