[package]
name = "iml-manager-cli"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
combine = "=4.0.0-beta.1"
console = "0.9"
dotenv = "0.15"
futures = "0.3"
hostlist-parser = "0.1"
iml-wire-types = { path = "../iml-wire-types", version = "0.2" }
iml-manager-client = { path = "../iml-manager-client", version = "0.1.0" }
indicatif = "0.13"
prettytable-rs = "0.8"
reqwest = { version = "0.10", features = ["default-tls", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
spinners = "1.0.0"
structopt = "0.2"
tokio = { version = "0.2", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.1"
number-formatter = { path = "../number-formatter", version = "0.1" }
dialoguer = "0.5.0"

[dependencies.regex]
version = "1.3"
default-features = false
features = ["std"]

[[bin]]
name = "iml"
path = "src/main.rs"
