[package]
name = "iml-duration-picker"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
seed = "0.3.7"
log = "0.4"
web-sys = { version = "0.3", features = ["Event", "EventTarget", "Element", "HtmlInputElement", "ValidityState"]}
wasm-bindgen = {version = "0.2.48"}
iml-tooltip = { path = "../iml-tooltip", version = "0.1" }
iml-utils = { path = "../iml-utils", version = "0.1" }
bootstrap-components = { path = "../bootstrap-components", version = "0.1" }

[dev-dependencies]
wasm-bindgen-test = "0.2"
insta = "0.8.1"