[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-journal"
version = "0.3.0"

[dependencies]
futures = "0.3"
iml-manager-env = {path = "../../iml-manager-env", version = "0.3"}
iml-rabbit = {path = "../../iml-rabbit", version = "0.3"}
iml-service-queue = {path = "../iml-service-queue", version = "0.3"}
iml-tracing = {version = "0.2", path = "../../iml-tracing"}
iml-wire-types = {path = "../../iml-wire-types", version = "0.3", features = ["postgres-interop"]}
lazy_static = "1.4.0"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
sqlx = {git = "https://github.com/jgrund/sqlx", branch = "support-offline-workspaces", default-features = false, features = ["time", "json", "macros", "offline", "postgres", "runtime-tokio"]}
thiserror = "1.0"
time = {version = "0.2", features = ["serde"]}
tokio = {version = "0.2", features = ["macros"]}

[dependencies.regex]
default-features = false
features = ["std"]
version = "1.3"

[dev-dependencies]
insta = "0.16"
