[package]
name = "iml-orm"
version = "0.2.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4", default_features = false, features = ["postgres", "r2d2", "chrono", "serde_json"], optional = true }
futures = { version = "0.3", optional = true }
iml-manager-env = { path = "../iml-manager-env", version = "0.2.0", optional = true }
ipnetwork = "0.16"
r2d2 = {version = "0.8", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = { version = "1.0", optional = true }
tokio-diesel = { git = "https://github.com/jgrund/tokio-diesel", optional = true }
tokio-postgres = { version = "0.5", optional = true }
tracing = { version = "0.1", optional = true }
warp = { version = "0.2", optional = true }
wbem-client = { path = "../wbem-client", version = "0.1", optional = true }

[features]
postgres-interop = ["diesel", "iml-manager-env", "r2d2", "tokio-diesel", "thiserror", "futures"]
tokio-postgres-interop = ["tokio-postgres"]
wbem-interop = ["wbem-client"]
wasm = ["chrono/wasmbind"]
warp-filters = ["tracing", "warp"]