[package]
name = "iml-fs"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
bootstrap-components = { path = "../bootstrap-components", version = "0.1" }
cfg-if = "0.1"
console_log = { version = "0.1", optional = true }
futures = "0.1"
iml-action-dropdown = { path = "../iml-action-dropdown", version = "0.1" }
iml-alert-indicator = { path = "../iml-alert-indicator", version = "0.1" }
iml-environment = { path = "../iml-environment", version = "0.1" }
iml-lock-indicator = { path = "../iml-lock-indicator", version = "0.1" }
iml-paging = { path = "../iml-paging", version = "0.1" }
iml-pie-chart = { path = "../iml-pie-chart", version = "0.1" }
iml-tooltip = { path = "../iml-tooltip", version = "0.1" }
iml-utils = { path = "../iml-utils", version = "0.1" }
iml-wire-types = "0.2"
iml-stratagem = { path = "../iml-stratagem", version = "0.1" }
number-formatter = { path = "../../number-formatter", version = "0.1" }
log = "0.4"
seed = "=0.4.1"
natord = "1.0.9"
serde = { version = "1", features = ['derive'] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"]}
web-sys = "0.3"


[dev-dependencies]
wasm-bindgen-test = "0.2"
insta = "0.11"
