[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-device"
version = "0.3.0"

[dependencies]
device-types = {path = "../../device-scanner/device-types", version = "0.2"}
futures = "0.3"
im = {version = "15.0", features = ["serde"]}
iml-change = {path = "../../iml-change", version = "0.1"}
iml-influx = {path = "../../iml-influx", version = "0.1"}
iml-manager-env = {path = "../../iml-manager-env", version = "0.3"}
iml-postgres = {path = "../../iml-postgres", version = "0.3"}
iml-rabbit = {path = "../../iml-rabbit", version = "0.3"}
iml-service-queue = {path = "../iml-service-queue", version = "0.3"}
iml-tracing = {version = "0.2", path = "../../iml-tracing"}
iml-wire-types = {path = "../../iml-wire-types", version = "0.3", features = ["postgres-interop"]}
influx_db_client = {version = "0.4", default-features = false, features = ["rustls-tls"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"
tokio = {version = "0.2", features = ["macros", "rt-threaded"]}
url = "2.1.1"
warp = "0.2"

[dev-dependencies]
chrono = "0.4"
dotenv = "0.15"
insta = {version = "0.16", features = ["redactions"]}
tokio-test = "0.2"
