[package]
name = "liblustreapi-types"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
libc = "0.2.64"

[build-dependencies]
bindgen = "0.49.0"
