[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-sfa"
version = "0.5.0"

[dependencies]
async-trait = "0.1"
futures = "0.3"
iml-change = {path = "../iml-change", version = "0.5"}
iml-manager-env = {version = "0.5", path = "../iml-manager-env"}
iml-postgres = {path = "../iml-postgres", version = "0.5"}
iml-request-retry = {path = "../iml-request-retry", version = "0.5"}
iml-tracing = {version = "0.5", path = "../iml-tracing"}
iml-wire-types = {path = "../iml-wire-types", version = "0.5", features = ["wbem-interop", "postgres-interop"]}
serde = "1"
thiserror = "1.0"
tokio = {version = "0.2", features = ["macros", "time", "rt-threaded"]}
unzip-n = "0.1.2"
url = "2.1"
wbem-client = {version = "0.5", path = "../wbem-client"}
