[package]
name = "liblustreapi"
version = "0.3.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
libc = "0.2.64"
errno = "0.2"
tracing = "0.1"
libloading = "0.5"
liblustreapi-types = { path = "../liblustreapi-types", version = "0.3"}
