[package]
name = "iml-grafana-chart"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
seed = "=0.4.1"
serde = { version = "1", features = ['derive'] }
serde_urlencoded = "0.6.1"
iml-environment = { path = "../iml-environment", version = "0.1" }