[package]
name = "iml-service-queue"
version = "0.2.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
iml-rabbit = { path = "../../iml-rabbit", version = "0.2.0" }
iml-wire-types = { path = "../../iml-wire-types", version = "0.2" }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"