[package]
name = "iml-sleep"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
seed = "=0.4.1"
futures = "0.1"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"]}

[dev-dependencies]
wasm-bindgen-test = "0.2"
insta = "0.11"