[package]
name = "iml-action-dropdown"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
seed = "=0.4.1"
serde = { version = "1", features = ['derive'] }
serde_json = "1.0"
futures = "0.1"
log = "0.4"
iml-tooltip = { path = "../iml-tooltip", version = "0.1" }
iml-sleep = { path = "../iml-sleep", version = "0.1" }
iml-utils = { path = "../iml-utils", version = "0.1" }
iml-wire-types = { path = "../../iml-wire-types", version = "0.2" }

[dev-dependencies]
wasm-bindgen-test = "0.2"
insta = "0.11"