[package]
name = "iml-action-dropdown"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib"]

[dependencies]
seed = { git = "https://github.com/David-OConnor/seed", rev = "67bd932c2cf95e765ba14efa7d6e55ce4064a920" }
serde = { version = "1", features = ['derive'] }
serde_json = "1.0.39"
futures = "0.1.25"
wasm-bindgen = { version = "0.2.40", features = ["serde-serialize"]}
web-sys = { version = "0.3.17", features = ["CustomEvent", "CustomEventInit", "Event", "EventTarget", "Element"]}
js-sys = "0.3.17"
console_error_panic_hook = "0.1.6"


[dev-dependencies]
wasm-bindgen-test = "0.2"
insta = "0.7.4"
