[package]
name = "iml-postgres"
version = "0.3.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
tokio-postgres = "0.5"
futures = "0.3"
tracing = "0.1"
iml-manager-env = { path = "../iml-manager-env", version = "0.3" }
deadpool-postgres = { version = "0.5", optional = true }

[features]
pool = ["deadpool-postgres"]
