[package]
authors = ["EMF Team <emf@whamcloud.com>"]
edition = "2018"
name = "emf-tracing"
version = "0.3.0"

[dependencies]
tokio = {version = "0.2", features = ["signal", "rt-core"]}
tracing = "0.1"
tracing-subscriber = "0.2"
