[package]
authors = ["IML Team <iml@whamcloud.com>"]
description = "shared device types used throughout device-scanner and IML"
edition = "2018"
license = "MIT"
name = "device-types"
version = "0.3.0"

[dependencies]
im = {version = "15.0", features = ["serde"]}
serde = {version = "1", features = ["derive"]}
tracing = "0.1"

[dev-dependencies]
insta = "0.15"
serde_json = "1.0"
