[package]
name = "iml-action-client"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
futures = "0.3"
iml-action-runner = { path = "../iml-services/iml-action-runner", version = "0.3" }
iml-manager-env = { path = "../iml-manager-env", version = "0.3" }
iml-wire-types = { path = "../iml-wire-types", version = "0.3" }
reqwest = { version = "0.10", features = ["rustls-tls", "json", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0"
uuid = { version = "0.8", features = ["v4"] }
