[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-action-runner"
version = "0.3.0"

[dependencies]
device-types = "0.1"
futures = "0.3"
iml-device = {path = "../iml-device", version = "0.3"}
iml-manager-env = {path = "../../iml-manager-env", version = "0.3"}
iml-postgres = {path = "../../iml-postgres", version = "0.3"}
iml-rabbit = {path = "../../iml-rabbit", version = "0.3", features = ["warp-filters"]}
iml-service-queue = {path = "../iml-service-queue", version = "0.3"}
iml-tracing = {version = "0.2", path = "../../iml-tracing"}
iml-util = {path = "../../iml-util", version = "0.3"}
iml-wire-types = {path = "../../iml-wire-types", version = "0.3"}
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"
tokio = {version = "0.2", features = ["rt-threaded"]}
tokio-runtime-shutdown = {path = "../../tokio-runtime-shutdown", version = "0.3"}
tracing = "0.1"
warp = "0.2"

[dev-dependencies]
dotenv = "0.15"
iml-agent-comms = {path = "../../iml-agent-comms", version = "0.3"}
rand = "0.7"
tokio-test = "0.2"
