[package]
authors = ["IML Team <iml@whamcloud.com>"]
description = "IML Systemd Library"
edition = "2018"
license = "MIT"
name = "iml-systemd"
version = "0.5.0"

[dependencies]
futures = "0.3"
iml-cmd = {path = "../iml-cmd", version = "0.5"}
iml-wire-types = {path = "../iml-wire-types", version = "0.5"}
serde = {version = "1", features = ['derive']}
serde_json = "1.0"
tokio = {version = "0.2", features = ["net", "stream", "time"]}
tracing = "0.1"
