[package]
name = "iml-services"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
lapin-futures = "0.18.0"
futures = "0.1.26"
tokio = "0.1.18"
tokio-timer = "0.2.10"
env_logger = "0.6.1"
log = "0.4.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
failure = "0.1.5"
warp = "0.1.15"
http = "0.1.16"
hyper = "0.12.25" 
iml-wire-types = { path = "../iml-wire-types", version = "0.1.0" }
iml-rabbit = { path = "../iml-rabbit", version = "0.1.0" }
iml-manager-env = { path = "../iml-manager-env", version = "0.1.0" }
iml-manager-messaging = { path = "../iml-manager-messaging", version = "0.1.0" }
tokio-runtime-shutdown = { path = "../tokio-runtime-shutdown", version = "0.1.0" }
parking_lot = "0.7"

[[bin]]
name = "iml-stratagem"
path = "src/services/stratagem.rs"

[[bin]] 
name = "iml-action-runner"
path = "src/services/action_runner/main.rs"