[package]
name = "iml-request-retry"
version = "0.1.0"
description = "IML async request retry Library"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
tokio = "0.2"
rand = "0.7"
tracing = "0.1"

[dev-dependencies]
tokio-test = "0.2"
http = "0.2"
reqwest = { version = "0.10", features = ["json"] }
url = "2.1"
rand_xorshift = "0.2.0"
warp = "0.2"
serde = { version = "1", features = ['derive'] }
serde_json = "1.0"

[[example]]
name = "demo-server-client"
path = "examples/demo-server-client.rs"

