name: prod-release
on:
  push:
    tags:
      - v*r5.1
    branches:
      - master
jobs:
  push_rust_iml:
    name: Push to Copr prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Push RPM
        uses: ./.github/actions/copr-rust
        env:
          PROD: true
          OWNER: managerforlustre
          PROJECT: manager-for-lustre-5.1
          PACKAGE: rust-iml
          SPEC: rust-iml.spec
          WORKSPACE: ${{ github.workspace }}
          RUSTUP_TOOLCHAIN: beta-x86_64-unknown-linux-gnu
          KEY: ${{ secrets.key }}
          IV: ${{ secrets.iv }}
  push_iml_wasm:
    name: Push to Copr prod (WASM)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Push RPM
        uses: ./.github/actions/copr-wasm
        env:
          PROD: true
          OWNER: managerforlustre
          PROJECT: manager-for-lustre-5.1
          PACKAGE: iml-wasm-components
          SPEC: iml-wasm-components/iml-wasm-components.spec
          WORKSPACE: ${{ github.workspace }}/iml-wasm-components
          KEY: ${{ secrets.key }}
          IV: ${{ secrets.iv }}
